# file: .github/workflows/first-workflow.yml

name: first-workflow
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      - uses: actions/checkout@v2
      # run – произвольная bash-команда
      - uses: actions/setup-node@v1
        name: 'setup node'
        with:
          node-version: '13.x'
      #- run: make setup
      #- run: make start
      #- run: make test
      #- run: make lint
      - run: npm install
      - run: npm run build
      - run: npm start
      - run: npm test
