# file: .github/workflows/first-workflow.yml

name: first-workflow
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      - uses: actions/checkout@v2
      - name: 'setup node'
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: make setup
      - run: make test
      - run: make lint
